spring:
  datasource:
    url: jdbc:h2:mem:project
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: project-service

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8070}/eureka/
